version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      BOT_TOKEN: $BOT_TOKEN
      POSTGRES_DSN: $POSTGRES_DSN
      MASTERS_URLS: $MASTERS_URLS
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: $POSTGRES_DB_NAME
      POSTGRES_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    ports:
      - "80:80"
    volumes:
      - .:/app
    networks:
      - app-network

volumes:
  postgres_data_prod:

networks:
  app-network:
